version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: recostream-db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-recostream}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-recostream}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: recostream-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@<your_db_host>:5432/${DB_NAME:-recostream}
      - FRONTEND_BUILD_PATH=/app/frontend/dist
      - TMDB_API_KEY=${TMDB_API_KEY:-your_tmdb_api_key_here}
      - SECRET_KEY=${SECRET_KEY:-dev_secret_key}
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  postgres_data:
