services:
  - type: web
    name: recostream-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recostream-db
          property: connectionString
      - key: TMDB_API_KEY
        value: your_tmdb_api_key_here
      - key: SECRET_KEY
        value: dev_secret_key
    autoDeploy: true
    healthCheckPath: /health
    startCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port 8000

databases:
  - name: recostream-db
    plan: free
